const products = [
  {id:1,name:'Poulet rôti',category:'Plats à emporter',price:1500,emoji:'🍗',desc:'Portion à emporter'},
  {id:2,name:'Pommes de terre rôties',category:'Plats à emporter',price:500,emoji:'🥔',desc:'Portion à emporter'},
  {id:3,name:'Riz cantonais',category:'Plats à emporter',price:500,emoji:'🍚',desc:'Portion à emporter'},
  {id:4,name:'Frites',category:'Plats à emporter',price:500,emoji:'🍟',desc:'Portion à emporter'},
  {id:5,name:'Part de quiche',category:'Plats à emporter',price:400,emoji:'🥧',desc:'Part individuelle'},
  {id:6,name:'Salade César',category:'Plats à emporter',price:900,emoji:'🥗',desc:'Salade composée'},
  {id:7,name:'Salade fraîcheur',category:'Plats à emporter',price:800,emoji:'🥗',desc:'Salade composée'},
  {id:8,name:'Plat du jour',category:'Plats à emporter',price:1000,emoji:'🍽️',desc:'Préparation du jour'},
  {id:9,name:'Mousse au chocolat',category:'Desserts',price:500,emoji:'🍫',desc:'Dessert maison'},
  {id:10,name:'Salade de fruits',category:'Desserts',price:500,emoji:'🍍',desc:'Fruits frais'},
  {id:11,name:'Glace Magnum',category:'Desserts',price:300,emoji:'🍦',desc:'À conserver au frais'},
  {id:12,name:'Glace Cornetto',category:'Desserts',price:300,emoji:'🍦',desc:'À conserver au frais'},
  {id:13,name:'Brochette de bonbons',category:'Desserts',price:200,emoji:'🍬',desc:'Confiserie'},
  {id:14,name:'Pot citrouille / ananas',category:'Desserts',price:600,emoji:'🍍',desc:'Dessert frais'},
  {id:15,name:'Coca-Cola 33 cl',category:'Boissons',price:300,emoji:'🥤',desc:'Canette fraîche'},
  {id:16,name:'Orangina 33 cl',category:'Boissons',price:300,emoji:'🥤',desc:'Canette fraîche'},
  {id:17,name:'Tulem 33 cl',category:'Boissons',price:300,emoji:'🥤',desc:'Canette fraîche'},
  {id:18,name:'Petite bouteille d’eau',category:'Boissons',price:200,emoji:'💧',desc:'Bouteille fraîche'}
];
const categories=['Tous','Plats à emporter','Desserts','Boissons'];
const categoryImages={'Plats à emporter':'./assets-plats.png','Desserts':'./assets-desserts.png','Boissons':'./assets-boissons.png'};
const cart=[]; let currentCategory='Tous'; let selectedMode='Sur place'; let selectedPayment=''; let paymentCash=0; const demoTaxRate=0;
const storageKey='snack-des-lilas-demo-v1';
const state=JSON.parse(localStorage.getItem(storageKey)||'null')||{nextOrder:1048,sales:[],refunds:[],cashOpen:true,openedAt:new Date().toISOString(),available:{},discountPercent:0,audit:[],lastHash:'GENESIS',users:[{id:1,name:'Marie',role:'Responsable',active:true},{id:2,name:'Compte caisse',role:'Caissier',active:true}],session:{name:'Marie',role:'Responsable'},settings:{name:'Snack des Lilas',ridet:'',address:'Lotissement Les Lilas, Nouvelle-Calédonie',phone:'+687 83.59.72',email:'snack.des.lilas@gmail.com',taxRates:''}};
state.audit=state.audit||[];state.refunds=state.refunds||[];state.lastHash=state.lastHash||'GENESIS';state.available=state.available||{};state.stock=state.stock||{};products.forEach(product=>{if(state.stock[product.id]===undefined)state.stock[product.id]=20;});state.users=state.users||[{id:1,name:'Marie',role:'Responsable',active:true}];state.session=state.session||{name:'Marie',role:'Responsable'};state.settings={name:'Snack des Lilas',ridet:'',address:'Lotissement Les Lilas, Nouvelle-Calédonie',phone:'+687 83.59.72',email:'snack.des.lilas@gmail.com',taxRates:'',...(state.settings||{})};
state.catalog=state.catalog||products.map(product=>({...product}));products.splice(0,products.length,...state.catalog);products.forEach(product=>{if(state.stock[product.id]===undefined)state.stock[product.id]=20;});
const money=value=>`${new Intl.NumberFormat('fr-FR').format(value)} F`;
const $=selector=>document.querySelector(selector);
function save(){localStorage.setItem(storageKey,JSON.stringify(state));}
function simpleHash(value){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash+=((hash<<1)+(hash<<4)+(hash<<7)+(hash<<8)+(hash<<24));}return(`00000000${(hash>>>0).toString(16)}`).slice(-8);}
function audit(action,details){const event={id:`AUD-${Date.now()}-${Math.floor(Math.random()*1000)}`,action,details,user:'Marie · Responsable',createdAt:new Date().toISOString(),previousHash:state.lastHash};event.hash=simpleHash(JSON.stringify(event));state.audit.push(event);state.lastHash=event.hash;save();}
function renderCategories(){const el=$('#categoryTabs');el.innerHTML=categories.map(c=>`<button class="category-tab ${c===currentCategory?'active':''}" data-category="${c}" type="button">${c}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{currentCategory=b.dataset.category;renderCategories();renderProducts();}));}
function isAvailable(product){return state.available[product.id]!==false&&Number(state.stock[product.id])>0;}
function renderProducts(){const query=$('#searchInput').value.toLowerCase();const visible=products.filter(p=>isAvailable(p)&&(currentCategory==='Tous'||p.category===currentCategory)&&`${p.name} ${p.category}`.toLowerCase().includes(query));$('#productGrid').innerHTML=visible.map(p=>`<button class="product-card" data-product="${p.id}" type="button"><img class="product-image" src="${categoryImages[p.category]}" alt="" /><div class="product-content"><span class="product-kicker">${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><span class="product-price">${money(p.price)}</span></div></button>`).join('')||'<p style="color:#887a72;font-size:13px">Aucun produit disponible.</p>';$('#productGrid').querySelectorAll('.product-card').forEach(b=>b.addEventListener('click',()=>addProduct(Number(b.dataset.product))));}
function addProduct(id){const product=products.find(p=>p.id===id);const line=cart.find(l=>l.id===id);if(line)line.qty++;else cart.push({...product,qty:1});renderCart();}
function totals(){const subtotal=cart.reduce((sum,l)=>sum+l.price*l.qty,0);const discount=Math.round(subtotal*(Number(state.discountPercent||0)/100));const taxable=subtotal-discount;const tax=Math.round(taxable*demoTaxRate);return{subtotal,discount,tax,total:taxable+tax};}
function renderCart(){if(!cart.length){$('#orderLines').innerHTML='<div class="empty-order"><div class="empty-icon">＋</div><strong>Le panier est vide</strong><span>Ajoutez un produit pour commencer</span></div>';}else{$('#orderLines').innerHTML=cart.map(l=>`<div class="order-line"><div><span class="line-name">${l.name}</span><span class="line-sub">${l.category} · ${money(l.price)} l’unité</span><div class="quantity-control"><button data-action="minus" data-id="${l.id}" type="button">−</button><span>${l.qty}</span><button data-action="plus" data-id="${l.id}" type="button">＋</button></div></div><span class="line-price">${money(l.price*l.qty)}</span></div>`).join('');$('#orderLines').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.id),b.dataset.action)));}const t=totals();$('#subtotal').textContent=money(t.subtotal);$('#discountAmount').textContent=`− ${money(t.discount)}`;$('#discountLabel').textContent=t.discount?`(${state.discountPercent} %)`:' ';$('#discountLine').classList.toggle('hidden',!t.discount);$('#tax').textContent=money(t.tax);$('#total').textContent=money(t.total);$('#payTotal').textContent=money(t.total);$('#modalTotal').textContent=money(t.total);$('#payButton').disabled=!cart.length;}
function changeQty(id,action){const line=cart.find(l=>l.id===id);if(!line)return;line.qty+=action==='plus'?1:-1;if(line.qty<=0)cart.splice(cart.indexOf(line),1);renderCart();}
function openModal(id){$(`#${id}`).classList.remove('hidden');}function closeModal(id){$(`#${id}`).classList.add('hidden');}
function renderProductTable(){const table=products.map(p=>`<div class="admin-row"><div><strong>${p.name}</strong><small>${p.category} · ${p.desc||'Sans description'}</small></div><label class="inline-price"><input data-edit-price="${p.id}" type="number" min="0" step="50" value="${p.price}" /><span>F</span></label><button class="availability ${isAvailable(p)?'on':''}" data-toggle-product="${p.id}" type="button">${isAvailable(p)?'Disponible':'Indisponible'}</button></div>`).join('');$('#productTable').innerHTML=table;$('#productTable').querySelectorAll('[data-toggle-product]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.toggleProduct;const product=products.find(p=>p.id===Number(id));const available=!isAvailable(product);state.available[id]=available;audit('Disponibilité produit',`${product.name} · ${available?'disponible':'indisponible'}`);renderProductTable();renderProducts();}));$('#productTable').querySelectorAll('[data-edit-price]').forEach(input=>input.addEventListener('change',()=>{const product=products.find(p=>p.id===Number(input.dataset.editPrice));const price=Math.max(0,Number(input.value)||0);if(product.price===price)return;const previous=product.price;product.price=price;state.catalog=products.map(item=>({...item}));audit('Prix produit modifié',`${product.name} · ${money(previous)} → ${money(price)}`);save();renderProductTable();renderProducts();}));}
function createProduct(){const name=$('#newProductName').value.trim();const category=$('#newProductCategory').value;const price=Math.max(0,Number($('#newProductPrice').value)||0);const desc=$('#newProductDescription').value.trim()||'Produit du catalogue';if(!name||!price){$('#productMessage').textContent='Renseignez un nom et un prix.';return;}const product={id:Date.now(),name,category,price,desc,emoji:'🍽️'};products.push(product);state.catalog=products.map(item=>({...item}));state.stock[product.id]=20;audit('Produit créé',`${name} · ${money(price)}`);save();$('#newProductName').value='';$('#newProductPrice').value='';$('#newProductDescription').value='';$('#productMessage').textContent='Produit ajouté au catalogue.';renderProductTable();renderProducts();}
function renderStocks(){const low=products.filter(p=>state.stock[p.id]<=5).length;$('#stockSummary').innerHTML=`<div><span>Références suivies</span><strong>${products.length}</strong></div><div><span>Alertes de rupture</span><strong class="${low?'warning-text':''}">${low}</strong></div>`;$('#stockTable').innerHTML=products.map(p=>{const quantity=Number(state.stock[p.id]);return`<div class="stock-row"><div><strong>${p.name}</strong><small>${p.category}</small></div><span class="stock-quantity ${quantity<=5?'low':''}">${quantity} unités</span><div class="stock-actions"><button data-stock-action="minus" data-stock-id="${p.id}" type="button">−</button><button data-stock-action="plus" data-stock-id="${p.id}" type="button">＋</button></div></div>`;}).join('');$('#stockTable').querySelectorAll('[data-stock-action]').forEach(button=>button.addEventListener('click',()=>adjustStock(Number(button.dataset.stockId),button.dataset.stockAction==='plus'?1:-1)));}
function adjustStock(id,delta){const product=products.find(p=>p.id===id);state.stock[id]=Math.max(0,Number(state.stock[id])+delta);audit('Ajustement stock',`${product.name} · ${delta>0?'+':''}${delta} · ${state.stock[id]} restant(s)`);save();renderStocks();renderProducts();}
function renderClosing(){const refunded=new Set(state.refunds.map(r=>r.saleNumber));const total=state.sales.filter(s=>!refunded.has(s.number)).reduce((s,x)=>s+x.total,0);const count=state.sales.length;$('#closingStatus').innerHTML=state.cashOpen?'<span class="status-pill open">● Caisse ouverte</span>':'<span class="status-pill closed">● Caisse clôturée</span>';$('#closingSummary').innerHTML=`<div><span>Ventes enregistrées</span><strong>${count}</strong></div><div><span>Total encaissé</span><strong>${money(total)}</strong></div><div><span>Remboursements</span><strong>${state.refunds.length}</strong></div>`;$('#closeCashButton').disabled=!state.cashOpen;$('#closeCashButton').style.display=state.cashOpen?'flex':'none';$('#cashOpening').style.display=state.cashOpen?'none':'block';$('#historyList').innerHTML=state.sales.slice(-8).reverse().map(s=>{const isRefunded=refunded.has(s.number);return`<div class="history-row ${isRefunded?'refunded':''}"><span>#${s.number} · ${s.payment}${isRefunded?' · Remboursé':''}</span><strong>${money(s.total)}</strong>${isRefunded?'':'<button class="refund-button" data-refund="'+s.number+'" type="button">Rembourser</button>'}</div>`;}).join('')||'<p class="modal-note">Aucune vente enregistrée aujourd’hui.</p>';$('#historyList').querySelectorAll('[data-refund]').forEach(b=>b.addEventListener('click',()=>refundSale(Number(b.dataset.refund))));}
function renderDashboard(){const refunded=new Set(state.refunds.map(r=>r.saleNumber));const sales=state.sales.filter(s=>!refunded.has(s.number));const revenue=sales.reduce((sum,s)=>sum+s.total,0);const counts={};const payments={};sales.forEach(s=>{payments[s.payment]=(payments[s.payment]||0)+s.total;s.lines.forEach(line=>{counts[line.name]=(counts[line.name]||0)+line.qty;});});const best=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];$('#dashRevenue').textContent=money(revenue);$('#dashOrders').textContent=sales.length;$('#dashAverage').textContent=money(sales.length?Math.round(revenue/sales.length):0);$('#dashBest').textContent=best?best[0]:'—';$('#dashBestNote').textContent=best?`${best[1]} vendu(s)`:'Aucune vente';$('#dashOrdersNote').textContent=sales.length?`${sales.filter(s=>s.mode==='Sur place').length} sur place`:'Aucune vente';$('#dashAverageNote').textContent=`Sur ${sales.length} commande(s)`;$('#dashPayments').innerHTML=sales.length?`<span class="status-dot"></span>${Object.entries(payments).map(([payment,total])=>`${payment} : ${money(total)}`).join(' · ')}`:'<span class="status-dot"></span> Aucun paiement enregistré.';}
function renderOrders(){const queue=state.sales.filter(s=>!state.refunds.some(r=>r.saleNumber===s.number)&&(s.status||'À préparer')!=='Terminée');$('#orderQueue').innerHTML=queue.slice(-20).reverse().map(s=>{const status=s.status||'À préparer';const lines=s.lines.map(line=>`<div><span>${line.qty} × ${line.name}</span><strong>${money(line.qty*line.price)}</strong></div>`).join('');return`<div class="queue-row"><div class="queue-number">#${s.number}</div><div class="queue-main"><strong>${s.customerName||'Client comptoir'}</strong><small>${s.mode} · ${s.lines.reduce((sum,l)=>sum+l.qty,0)} article(s) · ${new Date(s.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small><div class="queue-lines">${lines}</div>${s.note?`<div class="queue-note">Note : ${s.note}</div>`:''}</div><span class="queue-status ${String(status).toLowerCase().replace('à ','')}">${status}</span><button class="queue-action" data-order-status="${s.number}" type="button">${status==='À préparer'?'Marquer prête':status==='Prête'?'Appeler':'Terminer'}</button></div>`;}).join('')||'<p class="modal-note">Aucune commande à préparer.</p>';$('#orderQueue').querySelectorAll('[data-order-status]').forEach(button=>button.addEventListener('click',()=>{const sale=state.sales.find(s=>s.number===Number(button.dataset.orderStatus));if(!sale||sale.status==='Terminée')return;const status=sale.status||'À préparer';sale.status=status==='À préparer'?'Prête':status==='Prête'?'Appelée':'Terminée';audit('Statut commande',`Ticket #${sale.number} · ${sale.status}`);save();renderOrders();}));}
function renderInvoice(){const sale=state.sales[state.sales.length-1];if(!sale){$('#invoiceMessage').textContent='Aucune vente disponible pour une facture.';return;}$('#invoiceCustomer').value=sale.customerName||'';$('#invoicePhone').value=sale.customerPhone||'';$('#invoicePreview').innerHTML=`<div class="invoice-head"><strong>${state.settings.name}</strong><span>${state.settings.address}</span><span>${state.settings.phone} · ${state.settings.email}</span><span>RIDET : ${state.settings.ridet||'À renseigner'}</span></div><div class="invoice-number">FACTURE · F-${sale.number}</div><div class="invoice-client"><strong>Client</strong><span>${sale.customerName||'À renseigner'}</span><span>${sale.customerPhone||''}</span><span id="invoiceAddressPreview">${$('#invoiceAddress').value||'Adresse à renseigner'}</span></div><div class="receipt-lines">${sale.lines.map(l=>`<div><span>${l.qty} × ${l.name}</span><strong>${money(l.qty*l.price)}</strong></div>`).join('')}</div><div class="receipt-total"><span>Total à payer</span><strong>${money(sale.total)}</strong></div>`;}
function refundSale(number){const sale=state.sales.find(s=>s.number===number);if(!sale||state.refunds.some(r=>r.saleNumber===number))return;if(!confirm(`Confirmer le remboursement du ticket #${number} (${money(sale.total)}) ?`))return;state.refunds.push({id:`REF-${Date.now()}`,saleNumber:number,total:sale.total,payment:sale.payment,createdAt:new Date().toISOString(),user:state.session.name});audit('Remboursement',`Ticket #${number} · ${money(sale.total)} · motif à compléter`);save();renderClosing();}
function preparePayment(payment){selectedPayment=payment;const t=totals();$('#paymentDetail').innerHTML=payment==='Espèces'?'<label class="form-label">Montant reçu<input id="cashReceived" type="number" min="0" step="100" placeholder="Montant en F" /></label><div class="change-preview" id="changePreview">Monnaie à rendre : —</div><button class="confirm-payment" id="confirmPayment" type="button">Valider l’encaissement</button>':payment==='Paiement mixte'?'<label class="form-label">Part espèces<input id="mixedCash" type="number" min="0" step="100" placeholder="0 F" /></label><div class="change-preview">Le solde sera réglé par carte bancaire.</div><button class="confirm-payment" id="confirmPayment" type="button">Valider le paiement mixte</button>':'<button class="confirm-payment" id="confirmPayment" type="button">Confirmer ${payment}</button>';$('#confirmPayment').addEventListener('click',()=>{if(payment==='Espèces'){paymentCash=Number($('#cashReceived').value||0);if(paymentCash<totals().total){$('#changePreview').textContent=`Montant insuffisant · ${money(totals().total-paymentCash)} manquants`;return;}}if(payment==='Paiement mixte'){paymentCash=Number($('#mixedCash').value||0);if(paymentCash>totals().total){paymentCash=totals().total;}}registerPayment(payment);});if($('#cashReceived'))$('#cashReceived').addEventListener('input',()=>{const value=Number($('#cashReceived').value||0);$('#changePreview').textContent=value>=t.total?`Monnaie à rendre : ${money(value-t.total)}`:`Reste à régler : ${money(t.total-value)}`;});}
function registerPayment(payment){const t=totals();const change=payment==='Espèces'?paymentCash-t.total:0;const sale={number:state.nextOrder++,mode:selectedMode,payment,total:t.total,subtotal:t.subtotal,discount:t.discount,tax:t.tax,cashReceived:paymentCash,change,customerName:$('#customerName').value.trim(),customerPhone:$('#customerPhone').value.trim(),note:$('#orderNote').value.trim(),createdAt:new Date().toISOString(),lines:cart.map(l=>({id:l.id,name:l.name,qty:l.qty,price:l.price}))};state.sales.push(sale);sale.lines.forEach(line=>{state.stock[line.id]=Math.max(0,Number(state.stock[line.id])-line.qty);});audit('Encaissement',`Ticket #${sale.number} · ${money(sale.total)} · ${payment}`);$('#receiptContent').innerHTML=`<div class="receipt-meta"><span>Ticket #${sale.number}</span><span>${new Date().toLocaleString('fr-FR')}</span></div>${sale.customerName||sale.customerPhone?`<div class="receipt-customer">${sale.customerName?`<strong>${sale.customerName}</strong>`:''}${sale.customerPhone?`<span>${sale.customerPhone}</span>`:''}</div>`:''}<div class="receipt-lines">${sale.lines.map(l=>`<div><span>${l.qty} × ${l.name}</span><strong>${money(l.qty*l.price)}</strong></div>`).join('')}</div>${sale.note?`<div class="receipt-note">Note : ${sale.note}</div>`:''}${sale.discount?`<div class="receipt-total"><span>Remise ${state.discountPercent} %</span><strong>− ${money(sale.discount)}</strong></div>`:''}<div class="receipt-total"><span>Total ${sale.payment}</span><strong>${money(sale.total)}</strong></div>${sale.change?`<div class="change-receipt">Monnaie rendue : <strong>${money(sale.change)}</strong></div>`:''}`;cart.splice(0);state.discountPercent=0;$('#customerName').value='';$('#customerPhone').value='';$('#orderNote').value='';save();closeModal('paymentModal');openModal('receiptModal');renderCart();}
$('#searchInput').addEventListener('input',renderProducts);$('#clearOrder').addEventListener('click',()=>{cart.splice(0);renderCart();});document.querySelectorAll('.mode-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedMode=b.dataset.mode;$('#orderMode').textContent=selectedMode;}));
document.querySelector('#payButton').addEventListener('click',()=>openModal('paymentModal'));document.querySelector('#openDashboard').addEventListener('click',()=>openModal('dashboardModal'));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id);}));document.querySelectorAll('[data-payment]').forEach(b=>b.addEventListener('click',()=>preparePayment(b.dataset.payment)));$('#newOrderButton').addEventListener('click',()=>closeModal('receiptModal'));$('#discountButton').addEventListener('click',()=>{if(!cart.length)return;$('#managerPin').value='';$('#discountError').textContent='PIN de démonstration : 1234';openModal('discountModal');});document.querySelectorAll('[data-discount]').forEach(b=>b.addEventListener('click',()=>{if($('#managerPin').value!=='1234'){$('#discountError').textContent='PIN responsable incorrect.';return;}state.discountPercent=Number(b.dataset.discount);save();closeModal('discountModal');renderCart();}));
document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.screen==='produits'){renderProductTable();openModal('productModal');}if(b.dataset.screen==='cloture'){renderClosing();openModal('closingModal');}if(b.dataset.screen==='audit'){renderAudit();openModal('auditModal');}if(b.dataset.screen==='configuration'){renderSettings();openModal('settingsModal');}if(b.dataset.screen==='sauvegardes'){openModal('backupModal');}if(b.dataset.screen==='utilisateurs'){renderUsers();openModal('usersModal');}}));$('#closeCashButton').addEventListener('click',()=>{state.cashOpen=false;audit('Clôture de caisse',`Rapport Z · ${state.sales.length} vente(s)`);renderClosing();});$('#saveSettings').addEventListener('click',()=>{state.settings={name:$('#businessName').value,ridet:$('#businessRidet').value,address:$('#businessAddress').value,phone:$('#businessPhone').value,email:$('#businessEmail').value,taxRates:$('#businessTaxRates').value};audit('Configuration modifiée','Informations légales de l’établissement mises à jour');$('#settingsSaved').textContent='Configuration enregistrée localement.';});$('#exportCsv').addEventListener('click',exportSalesCsv);$('#exportJson').addEventListener('click',exportJson);$('#exportAudit').addEventListener('click',exportAudit);$('#importJson').addEventListener('click',()=>$('#backupFile').click());$('#backupFile').addEventListener('change',event=>{if(event.target.files[0])importJsonFile(event.target.files[0]);});$('#createUser').addEventListener('click',()=>{const name=$('#newUserName').value.trim();const role=$('#newUserRole').value;if(!name){$('#userMessage').textContent='Indiquez un nom.';return;}const user={id:Date.now(),name,role,active:true};state.users.push(user);audit('Utilisateur créé',`${name} · ${role}`);save();$('#newUserName').value='';renderUsers();$('#userMessage').textContent='Compte créé localement.';});
function cancelSale(number){const sale=state.sales.find(s=>s.number===number);if(!sale||sale.status==='Annulée')return;if(!confirm(`Annuler la commande #${sale.number} (${money(sale.total)}) ?`))return;sale.status='Annulée';sale.cancelledAt=new Date().toISOString();sale.cancelledBy=state.session.name;if(!sale.stockRestored){sale.lines.forEach(line=>{state.stock[line.id]=Number(state.stock[line.id])+line.qty;});sale.stockRestored=true;}audit('Annulation commande',`Ticket #${sale.number} · ${money(sale.total)} · ${state.session.name}`);save();renderOrders();if(!$('#closingModal').classList.contains('hidden'))renderClosing();if(!$('#dashboardModal').classList.contains('hidden'))renderDashboard();}
const originalRenderOrders=renderOrders;renderOrders=function(){originalRenderOrders();$('#orderQueue').querySelectorAll('.queue-row').forEach(row=>{const number=Number(row.querySelector('.queue-number')?.textContent.replace('#',''));const sale=state.sales.find(item=>item.number===number);if(!sale)return;if(sale.status==='Annulée'){row.remove();return;}const button=document.createElement('button');button.className='queue-action cancel-action';button.dataset.cancelOrder=number;button.type='button';button.textContent='Annuler';row.append(button);});$('#orderQueue').querySelectorAll('[data-cancel-order]').forEach(button=>button.addEventListener('click',()=>cancelSale(Number(button.dataset.cancelOrder))));};
const previousRenderClosing=renderClosing;renderClosing=function(){previousRenderClosing();$('#historyList').querySelectorAll('.history-row').forEach(row=>{const number=Number(row.textContent.match(/#(\d+)/)?.[1]);const sale=state.sales.find(item=>item.number===number);if(!sale||sale.status==='Annulée'||state.refunds.some(r=>r.saleNumber===number))return;const actions=row.querySelector('.history-actions')||row;const button=document.createElement('button');button.className='secondary-action cancel-action';button.dataset.cancelHistory=number;button.type='button';button.textContent='Annuler';actions.append(button);});$('#historyList').querySelectorAll('[data-cancel-history]').forEach(button=>button.addEventListener('click',()=>cancelSale(Number(button.dataset.cancelHistory))));const active=state.sales.filter(s=>s.status!=='Annulée'&&!state.refunds.some(r=>r.saleNumber===s.number));const total=active.reduce((sum,s)=>sum+s.total,0);$('#closingSummary').innerHTML=`<div><span>Ventes enregistrées</span><strong>${active.length}</strong></div><div><span>Total encaissé</span><strong>${money(total)}</strong></div><div><span>Remboursements</span><strong>${state.refunds.length}</strong></div>`;};
const previousRenderDashboard=renderDashboard;renderDashboard=function(){previousRenderDashboard();const sales=state.sales.filter(s=>s.status!=='Annulée'&&!state.refunds.some(r=>r.saleNumber===s.number));const revenue=sales.reduce((sum,s)=>sum+s.total,0);$('#dashRevenue').textContent=money(revenue);$('#dashOrders').textContent=sales.length;$('#dashAverage').textContent=money(sales.length?Math.round(revenue/sales.length):0);const payments={};sales.forEach(s=>payments[s.payment]=(payments[s.payment]||0)+s.total);$('#dashPayments').innerHTML=sales.length?`<span class="status-dot"></span>${Object.entries(payments).map(([payment,total])=>`${payment} : ${money(total)}`).join(' · ')}`:'<span class="status-dot"></span> Aucun paiement enregistré.';};
function updateCashUi(){const closed=!state.cashOpen;$('#payButton').disabled=closed||!cart.length;$('#payButton').title=closed?'Caisse clôturée · ouvrez la caisse pour encaisser':'Encaisser la commande';$('#discountButton').disabled=closed;$('.topbar-status').innerHTML=`<span class="status-dot"></span> Hors connexion · données locales · ${closed?'Caisse clôturée':'Caisse ouverte'}`;}document.querySelector('#closeCashButton').addEventListener('click',updateCashUi);
const previousRenderCart=renderCart;renderCart=function(){previousRenderCart();updateCashUi();};const previousAddProduct=addProduct;addProduct=function(id){if(!state.cashOpen){updateCashUi();return;}previousAddProduct(id);};const previousChangeQty=changeQty;changeQty=function(id,action){if(!state.cashOpen)return;previousChangeQty(id,action);};const previousRegisterPayment=registerPayment;registerPayment=function(payment){if(!state.cashOpen){closeModal('paymentModal');updateCashUi();return;}previousRegisterPayment(payment);};
function renderAudit(){let previous='GENESIS';let valid=true;for(const event of state.audit){const expected=simpleHash(JSON.stringify({...event,hash:undefined}));if(event.previousHash!==previous||event.hash!==expected)valid=false;previous=event.hash;}const intact=valid&&previous===state.lastHash;$('#auditIntegrity').innerHTML=`<span class="status-pill ${intact?'open':'closed'}">${intact?'● Chaîne intègre':'● Vérification nécessaire'}</span><span class="integrity-hash">Dernière empreinte : ${state.lastHash}</span>`;$('#auditList').innerHTML=state.audit.slice(-30).reverse().map(e=>`<div class="audit-row"><div><strong>${e.action}</strong><small>${e.details}</small></div><span>${new Date(e.createdAt).toLocaleString('fr-FR')}</span><code>${e.hash}</code></div>`).join('')||'<p class="modal-note">Aucune opération auditée.</p>';}
function renderSettings(){const s=state.settings;$('#businessName').value=s.name||'';$('#businessRidet').value=s.ridet||'';$('#businessAddress').value=s.address||'';$('#businessPhone').value=s.phone||'';$('#businessEmail').value=s.email||'';$('#businessTaxRates').value=s.taxRates||'';}
function renderSavedReceipt(sale){const discountPercent=sale.subtotal?Math.round((Number(sale.discount||0)/sale.subtotal)*100):0;$('#receiptContent').innerHTML=`<div class="receipt-meta"><span>Ticket #${sale.number}</span><span>${new Date(sale.createdAt).toLocaleString('fr-FR')}</span></div>${sale.customerName||sale.customerPhone?`<div class="receipt-customer">${sale.customerName?`<strong>${sale.customerName}</strong>`:''}${sale.customerPhone?`<span>${sale.customerPhone}</span>`:''}</div>`:''}<div class="receipt-lines">${sale.lines.map(l=>`<div><span>${l.qty} × ${l.name}</span><strong>${money(l.qty*l.price)}</strong></div>`).join('')}</div>${sale.note?`<div class="receipt-note">Note : ${sale.note}</div>`:''}${sale.discount?`<div class="receipt-total"><span>Remise ${discountPercent} %</span><strong>− ${money(sale.discount)}</strong></div>`:''}<div class="receipt-total"><span>Total ${sale.payment}</span><strong>${money(sale.total)}</strong></div>${sale.change?`<div class="change-receipt">Monnaie rendue : <strong>${money(sale.change)}</strong></div>`:''}`;}
function reopenSavedReceipt(number){const sale=state.sales.find(s=>s.number===number);if(!sale)return;renderSavedReceipt(sale);audit('Réimpression ticket',`Ticket #${sale.number}`);save();closeModal('closingModal');openModal('receiptModal');}
const originalRenderClosing=renderClosing;renderClosing=function(){originalRenderClosing();$('#historyList').querySelectorAll('.history-row').forEach(row=>{const number=Number(row.querySelector('[data-refund]')?.dataset.refund||row.textContent.match(/#(\d+)/)?.[1]);if(!number)return;const actions=document.createElement('div');actions.className='history-actions';actions.innerHTML=`<button class="secondary-action" data-reprint="${number}" type="button">Réimprimer</button>`;row.append(actions);});$('#historyList').querySelectorAll('[data-reprint]').forEach(b=>b.addEventListener('click',()=>reopenSavedReceipt(Number(b.dataset.reprint))));};
const permissions={Caissier:'Encaissement, consultation du catalogue',Responsable:'Caisse, remises, clôture, remboursements',Administrateur:'Toutes les fonctions et paramètres'};
function renderUsers(){const roleClass=role=>role.toLowerCase().replace('é','e');$('#usersList').innerHTML=state.users.map(user=>`<div class="user-row"><div class="user-initial">${user.name.charAt(0).toUpperCase()}</div><div class="user-edit"><div class="user-edit-fields"><label>Nom<input data-user-name="${user.id}" value="${user.name}" /></label><label>Rôle<select data-user-role="${user.id}"><option ${user.role==='Caissier'?'selected':''}>Caissier</option><option ${user.role==='Responsable'?'selected':''}>Responsable</option><option ${user.role==='Administrateur'?'selected':''}>Administrateur</option></select></label></div><small>${permissions[user.role]}</small><div class="user-edit-actions"><span class="role-badge ${roleClass(user.role)}">${user.role}</span><span class="user-state ${user.active?'active':''}">${user.active?'Actif':'Inactif'}</span><button class="secondary-action" data-user-save="${user.id}" type="button">Enregistrer</button><button class="secondary-action" data-user-toggle="${user.id}" type="button">${user.active?'Désactiver':'Activer'}</button></div></div></div>`).join('');$('#usersList').querySelectorAll('[data-user-save]').forEach(button=>button.addEventListener('click',()=>{const user=state.users.find(item=>item.id===Number(button.dataset.userSave));if(!user)return;const name=$(`[data-user-name="${user.id}"]`).value.trim();const role=$(`[data-user-role="${user.id}"]`).value;if(!name){return;}const changed=user.name!==name||user.role!==role;user.name=name;user.role=role;if(changed)audit('Utilisateur modifié',`${name} · ${role}`);save();renderUsers();renderSession();}));$('#usersList').querySelectorAll('[data-user-toggle]').forEach(button=>button.addEventListener('click',()=>{const user=state.users.find(item=>item.id===Number(button.dataset.userToggle));if(!user)return;user.active=!user.active;audit(user.active?'Utilisateur activé':'Utilisateur désactivé',`${user.name} · ${user.role}`);save();renderUsers();}));}
function renderSession(){const initials=state.session.name.split(' ').map(part=>part.charAt(0)).join('').slice(0,2).toUpperCase();$('#sessionButton').textContent=initials;$('#sessionButton').title=`${state.session.name} · ${state.session.role} · Verrouiller`;$('[data-screen="caisse"]').title=`Session : ${state.session.name} · ${state.session.role}`;applyPermissions();}
function applyPermissions(){const fullManagement=['caisse','produits','cloture','commandes','stocks','audit','configuration','sauvegardes','utilisateurs'];const access={Caissier:['caisse','commandes'],Responsable:fullManagement,Administrateur:fullManagement}[state.session.role]||['caisse'];document.querySelectorAll('.nav-button').forEach(button=>{button.style.display=access.includes(button.dataset.screen)?'':'none';});if(!access.includes('caisse'))document.querySelector('[data-screen="caisse"]').style.display='';const modalAccess={productModal:'produits',closingModal:'cloture',auditModal:'audit',settingsModal:'configuration',backupModal:'sauvegardes',usersModal:'utilisateurs',stockModal:'stocks'};Object.entries(modalAccess).forEach(([modal,screen])=>{if(!access.includes(screen)&&!$(`#${modal}`).classList.contains('hidden'))closeModal(modal);});}
function downloadFile(filename,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url);}
function exportSalesCsv(){const header='ticket;date;mode;paiement;sous_total;remise;tgc;total\n';const rows=state.sales.map(s=>[s.number,s.createdAt,s.mode,s.payment,s.subtotal,s.discount||0,s.tax,s.total].map(value=>`"${String(value).replaceAll('"','""')}"`).join(';')).join('\n');downloadFile(`snack-des-lilas-ventes-${new Date().toISOString().slice(0,10)}.csv`,header+rows,'text/csv;charset=utf-8');audit('Export CSV',`${state.sales.length} vente(s)`);$('#backupMessage').textContent='Export CSV téléchargé.';}
function exportJson(){downloadFile(`snack-des-lilas-sauvegarde-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');audit('Sauvegarde JSON','Export complet téléchargé');$('#backupMessage').textContent='Sauvegarde JSON téléchargée.';}
function exportAudit(){downloadFile(`snack-des-lilas-audit-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state.audit,null,2),'application/json');$('#backupMessage').textContent='Journal d’audit téléchargé.';}
function importJsonFile(file){const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported||!Array.isArray(imported.sales)||!Array.isArray(imported.audit)||!imported.settings)throw new Error('Format invalide');if(!confirm('Restaurer cette sauvegarde remplacera les données locales actuelles. Continuer ?'))return;localStorage.setItem(storageKey,JSON.stringify(imported));location.reload();}catch(error){$('#backupMessage').textContent='Restauration refusée : fichier invalide.';}};reader.readAsText(file);}
document.querySelector('#sessionButton').addEventListener('click',()=>{audit('Verrouillage de caisse',`${state.session.name} · ${state.session.role}`);$('#loginPin').value='';$('#loginMessage').textContent='Responsable : 1234 · Caissier : 1111';openModal('loginModal');});let selectedLoginRole='Responsable';document.querySelectorAll('[data-login-role]').forEach(b=>b.addEventListener('click',()=>{selectedLoginRole=b.dataset.loginRole;document.querySelectorAll('[data-login-role]').forEach(x=>x.classList.toggle('selected',x===b));}));$('#unlockButton').addEventListener('click',()=>{const expected=selectedLoginRole==='Responsable'?'1234':'1111';if($('#loginPin').value!==expected){$('#loginMessage').textContent='PIN incorrect pour ce rôle.';return;}state.session={name:selectedLoginRole==='Responsable'?'Marie':'Compte caisse',role:selectedLoginRole};save();audit('Déverrouillage de caisse',`${state.session.name} · ${state.session.role}`);renderSession();closeModal('loginModal');});
document.querySelector('[data-screen="stocks"]').addEventListener('click',()=>{document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));document.querySelector('[data-screen="stocks"]').classList.add('active');renderStocks();openModal('stockModal');});document.querySelector('#printReceipt').addEventListener('click',()=>{document.body.classList.add('printing-ticket');window.print();setTimeout(()=>document.body.classList.remove('printing-ticket'),500);});
document.querySelector('#openDashboard').addEventListener('click',()=>{renderDashboard();openModal('dashboardModal');});
document.querySelector('[data-screen="commandes"]').addEventListener('click',()=>{document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));document.querySelector('[data-screen="commandes"]').classList.add('active');renderOrders();openModal('ordersModal');});$('#createProduct').addEventListener('click',createProduct);
document.querySelector('#invoiceButton').addEventListener('click',()=>{renderInvoice();closeModal('receiptModal');openModal('invoiceModal');});$('#backToReceipt').addEventListener('click',()=>{closeModal('invoiceModal');openModal('receiptModal');});$('#invoiceAddress').addEventListener('input',()=>{const preview=$('#invoiceAddressPreview');if(preview)preview.textContent=$('#invoiceAddress').value||'Adresse à renseigner';});$('#printInvoice').addEventListener('click',()=>{document.body.classList.add('printing-invoice');window.print();setTimeout(()=>document.body.classList.remove('printing-invoice'),500);});$('#saveInvoice').addEventListener('click',()=>{audit('Aperçu facture généré',`Facture F-${state.sales[state.sales.length-1]?.number||'—'}`);$('#invoiceMessage').textContent='Aperçu enregistré dans le journal local.';});
document.querySelector('#openCashButton').addEventListener('click',()=>{const opening=Math.max(0,Number($('#openingFloat').value)||0);state.cashOpen=true;state.openedAt=new Date().toISOString();state.openingFloat=opening;audit('Ouverture de caisse',`Fond initial · ${money(opening)}`);save();renderClosing();renderCart();});document.querySelector('#closeCashButton').addEventListener('click',()=>{$('#payButton').disabled=true;});if(!state.cashOpen)$('#payButton').disabled=true;
function updateClock(){$('#clock').textContent=new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date());}setInterval(updateClock,30000);updateClock();renderCategories();renderProducts();renderCart();renderSession();
